# Stage 1: Build
FROM node:20.12.2 AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Stage 2: Production
FROM node:20.12.2-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install --production

# Copy the build output from the builder stage
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/next.config.mjs ./
COPY --from=builder /app/package.json ./

# Expose the application port
EXPOSE 3000

# Run Next.js in production mode
CMD ["npm", "run", "start"]
