version: "3.9"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000" 
    depends_on:
      - server # Ensures the server starts before the client

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001" # Maps port 5000 of the host to the server's container
    env_file:
      - ./server/.env 
    depends_on:
      - mongo # Ensures MongoDB starts before the server

  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017" # Maps port 27017 of the host to the MongoDB container
    volumes:
      - mongo-data:/data/db # Persists MongoDB data

volumes:
  mongo-data:
